### ISSUE TITLE
Dialog Close press another side

### ISSUE THREAD

**Issue by re-LIFE** [vasu-bhardwaj/NoInternet#1]
what if the user presses the close button or another part, then the dialog still appears when not connected to the network

**Comment by Addynt** [comment]
I got the following errors when i open the network connection after clicking the button

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentTransaction androidx.fragment.app.FragmentManager.beginTransaction()' on a null object reference
        at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:219)
        at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:191)
        at com.graphicera.geu.InternetConnectionFiles.NoNet.hideDefaultDialog(NoNet.java:47)
        at com.graphicera.geu.InternetConnectionFiles.NoNet.Networkupdate(NoNet.java:32)
        at com.graphicera.geu.InternetConnectionFiles.NetworkMonitor.notifycallback(NetworkMonitor.java:74)
        at com.graphicera.geu.InternetConnectionFiles.NetworkMonitor.onReceive(NetworkMonitor.java:45)

Can you help...??

**Comment by vasu-bhardwaj** [comment]
Hi,
Now days i am not working on android.But when ever i will have time will look into the issue.


________________________________

**Comment by vasu-bhardwaj** [comment]
Hi,
Now days i am not working on android.But when ever i will have time will look into the issue.
- vasu_rb


________________________________

**Comment by Addynt** [comment]
Thank you for your reply.. your work was great to help me.. i have fixed my
issue.. i m still learning android.. Your work was inspiring.
